// Training modes. Each mode is pure data; behaviour lives in core/targets.js.
export const MODES = Object.freeze([
  {
    id: 'gridshot',
    name: 'GRIDSHOT',
    desc: 'Duvarda aynı anda 3 hedef. Vur, yenisi gelsin. Hız + doğruluk.',
    duration: 60,
    targets: 3,
    radius: 0.55,
    spread: { w: 14, h: 7 },
    kind: 'static',
    hitScore: 100,
    missPenalty: 25,
  },
  {
    id: 'flick',
    name: 'FLICK',
    desc: 'Tek hedef, geniş açı. Hedef belirir belirmez vur — tepki süren ölçülür.',
    duration: 60,
    targets: 1,
    radius: 0.6,
    spread: { w: 22, h: 10 },
    kind: 'flick',
    hitScore: 100,
    missPenalty: 15,
    spawnDelay: [0.25, 0.7],
  },
  {
    id: 'tracking',
    name: 'TRACKING',
    desc: 'Hareket eden hedefin üstünde kal. Basılı tut, puan aksın.',
    duration: 60,
    targets: 1,
    radius: 0.7,
    spread: { w: 16, h: 6 },
    kind: 'tracking',
    hitScore: 0,
    missPenalty: 0,
    trackScorePerSec: 120,
  },
  {
    id: 'precision',
    name: 'PRECISION',
    desc: 'Küçük hedefler, zamanla büzüşür. Yavaş ama tam isabet.',
    duration: 60,
    targets: 3,
    radius: 0.32,
    spread: { w: 12, h: 6 },
    kind: 'shrink',
    hitScore: 150,
    missPenalty: 40,
    shrinkTime: 3.2,
  },
  {
    id: 'spider',
    name: 'SPIDER',
    desc: 'Merkez → rastgele → merkez. Flick + geri dönüş disiplini.',
    duration: 60,
    targets: 1,
    radius: 0.55,
    spread: { w: 18, h: 8 },
    kind: 'spider',
    hitScore: 100,
    missPenalty: 20,
  },
]);

export function modeById(id) {
  return MODES.find((m) => m.id === id) || MODES[0];
}
